package employmentservices.model.job;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * JobDegree generated by hbm2java
 */
@Entity
@Table(name = "job_degree")
public class JobDegree implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2326717916045712165L;
	private int id;
	private String degreeName;
	private Set<JobPost> jobPosts = new HashSet<JobPost>(0);

	public JobDegree() {
	}

	public JobDegree(int id, String degreeName) {
		this.id = id;
		this.degreeName = degreeName;
	}

	public JobDegree(int id, String degreeName, Set<JobPost> jobPosts) {
		this.id = id;
		this.degreeName = degreeName;
		this.jobPosts = jobPosts;
	}

	@Id @GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "job_degree_generator")
	@SequenceGenerator(name="job_degree_generator", sequenceName = "job_degree_id_seq")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "degree_name", nullable = false, length = 20)
	public String getDegreeName() {
		return this.degreeName;
	}

	public void setDegreeName(String degreeName) {
		this.degreeName = degreeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobDegree")
	public Set<JobPost> getJobPosts() {
		return this.jobPosts;
	}

	public void setJobPosts(Set<JobPost> jobPosts) {
		this.jobPosts = jobPosts;
	}

}
