package employmentservices.model.seeker;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EducationDetail generated by hbm2java
 */
@Entity
@Table(name = "education_detail")
public class EducationDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8795315701255250794L;
	private EducationDetailId id;
	private SeekerProfile seekerProfile;
	private String instituteUniversityName;
	private Date startingDate;
	private Date completionDate;
	private String description;
	private String imagePath;

	public EducationDetail() {
	}

	public EducationDetail(EducationDetailId id, SeekerProfile seekerProfile, String instituteUniversityName,
			Date startingDate) {
		this.id = id;
		this.seekerProfile = seekerProfile;
		this.instituteUniversityName = instituteUniversityName;
		this.startingDate = startingDate;
	}

	public EducationDetail(EducationDetailId id, SeekerProfile seekerProfile, String instituteUniversityName,
			Date startingDate, Date completionDate, String description, String imagePath) {
		this.id = id;
		this.seekerProfile = seekerProfile;
		this.instituteUniversityName = instituteUniversityName;
		this.startingDate = startingDate;
		this.completionDate = completionDate;
		this.description = description;
		this.imagePath = imagePath;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "certificateDegreeName", column = @Column(name = "certificate_degree_name", nullable = false, length = 50)),
			@AttributeOverride(name = "major", column = @Column(name = "major", nullable = false, length = 50)) })
	public EducationDetailId getId() {
		return this.id;
	}

	public void setId(EducationDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seeker_id", nullable = false)
	public SeekerProfile getSeekerProfile() {
		return this.seekerProfile;
	}

	public void setSeekerProfile(SeekerProfile seekerProfile) {
		this.seekerProfile = seekerProfile;
	}

	@Column(name = "institute_university_name", nullable = false, length = 50)
	public String getInstituteUniversityName() {
		return this.instituteUniversityName;
	}

	public void setInstituteUniversityName(String instituteUniversityName) {
		this.instituteUniversityName = instituteUniversityName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "starting_date", nullable = false, length = 13)
	public Date getStartingDate() {
		return this.startingDate;
	}

	public void setStartingDate(Date startingDate) {
		this.startingDate = startingDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "completion_date", length = 13)
	public Date getCompletionDate() {
		return this.completionDate;
	}

	public void setCompletionDate(Date completionDate) {
		this.completionDate = completionDate;
	}

	@Column(name = "description", length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "image_path", length = 200)
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

}
