package employmentservices.model.seeker;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SeekerSkillSetId generated by hbm2java
 */
@Embeddable
public class SeekerSkillSetId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2390465180155354102L;
	private int seekerId;
	private int skillSetId;

	public SeekerSkillSetId() {
	}

	public SeekerSkillSetId(int seekerId, int skillSetId) {
		this.seekerId = seekerId;
		this.skillSetId = skillSetId;
	}

	@Column(name = "seeker_id", nullable = false)
	public int getSeekerId() {
		return this.seekerId;
	}

	public void setSeekerId(int seekerId) {
		this.seekerId = seekerId;
	}

	@Column(name = "skill_set_id", nullable = false)
	public int getSkillSetId() {
		return this.skillSetId;
	}

	public void setSkillSetId(int skillSetId) {
		this.skillSetId = skillSetId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeekerSkillSetId))
			return false;
		SeekerSkillSetId castOther = (SeekerSkillSetId) other;

		return (this.getSeekerId() == castOther.getSeekerId()) && (this.getSkillSetId() == castOther.getSkillSetId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSeekerId();
		result = 37 * result + this.getSkillSetId();
		return result;
	}

}
