package employmentservices.model.seeker;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SeekerTag generated by hbm2java
 */
@Entity
@Table(name = "seeker_tag")
public class SeekerTag implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2631044362280813427L;
	private int id;
	private SeekerProfile seekerProfile;
	private String tagText;

	public SeekerTag() {
	}

	public SeekerTag(int id, SeekerProfile seekerProfile, String tagText) {
		this.id = id;
		this.seekerProfile = seekerProfile;
		this.tagText = tagText;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seeker_id", nullable = false)
	public SeekerProfile getSeekerProfile() {
		return this.seekerProfile;
	}

	public void setSeekerProfile(SeekerProfile seekerProfile) {
		this.seekerProfile = seekerProfile;
	}

	@Column(name = "tag_text", nullable = false, length = 20)
	public String getTagText() {
		return this.tagText;
	}

	public void setTagText(String tagText) {
		this.tagText = tagText;
	}

}
