package employmentservices.model.seeker;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import employmentservices.model.job.JobPost;

/**
 * Currency generated by hbm2java
 */
@Entity
@Table(name = "currency")
public class Currency implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1866765345799092159L;
	private int id;
	private String currencyName;
	private Set<JobPost> jobPosts = new HashSet<JobPost>(0);
	private Set<SeekerProfile> seekerProfiles = new HashSet<SeekerProfile>(0);

	public Currency() {
	}

	public Currency(int id, String currencyName) {
		this.id = id;
		this.currencyName = currencyName;
	}

	public Currency(int id, String currencyName, Set<JobPost> jobPosts, Set<SeekerProfile> seekerProfiles) {
		this.id = id;
		this.currencyName = currencyName;
		this.jobPosts = jobPosts;
		this.seekerProfiles = seekerProfiles;
	}
	
	@Id @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "currency_generator")
	@SequenceGenerator(name = "currency_generator", sequenceName = "currency_id_seq")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "currency_name", nullable = false, length = 20)
	public String getCurrencyName() {
		return this.currencyName;
	}

	public void setCurrencyName(String currencyName) {
		this.currencyName = currencyName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "currency")
	public Set<JobPost> getJobPosts() {
		return this.jobPosts;
	}

	public void setJobPosts(Set<JobPost> jobPosts) {
		this.jobPosts = jobPosts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "currency")
	public Set<SeekerProfile> getSeekerProfiles() {
		return this.seekerProfiles;
	}

	public void setSeekerProfiles(Set<SeekerProfile> seekerProfiles) {
		this.seekerProfiles = seekerProfiles;
	}

}
