package employmentservices.model;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmployeeAmount generated by hbm2java
 */
@Entity
@Table(name = "employee_amount")
public class EmployeeAmount implements java.io.Serializable {

	private int id;
	private String amount;
	private Set<Company> companies = new HashSet<Company>(0);

	public EmployeeAmount() {
	}

	public EmployeeAmount(int id, String amount) {
		this.id = id;
		this.amount = amount;
	}

	public EmployeeAmount(int id, String amount, Set<Company> companies) {
		this.id = id;
		this.amount = amount;
		this.companies = companies;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "amount", nullable = false, length = 30)
	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeeAmount")
	public Set<Company> getCompanies() {
		return this.companies;
	}

	public void setCompanies(Set<Company> companies) {
		this.companies = companies;
	}

}
