package employmentservices.model;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExperienceDetail generated by hbm2java
 */
@Entity
@Table(name = "experience_detail")
public class ExperienceDetail implements java.io.Serializable {

	private ExperienceDetailId id;
	private SeekerProfile seekerProfile;
	private String companyName;
	private String position;
	private String description;
	private boolean isCurrentJob;
	private String imagePath;

	public ExperienceDetail() {
	}

	public ExperienceDetail(ExperienceDetailId id, SeekerProfile seekerProfile, String companyName, String position,
			boolean isCurrentJob) {
		this.id = id;
		this.seekerProfile = seekerProfile;
		this.companyName = companyName;
		this.position = position;
		this.isCurrentJob = isCurrentJob;
	}

	public ExperienceDetail(ExperienceDetailId id, SeekerProfile seekerProfile, String companyName, String position,
			String description, boolean isCurrentJob, String imagePath) {
		this.id = id;
		this.seekerProfile = seekerProfile;
		this.companyName = companyName;
		this.position = position;
		this.description = description;
		this.isCurrentJob = isCurrentJob;
		this.imagePath = imagePath;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "startDate", column = @Column(name = "start_date", nullable = false, length = 13)),
			@AttributeOverride(name = "endDate", column = @Column(name = "end_date", nullable = false, length = 13)) })
	public ExperienceDetailId getId() {
		return this.id;
	}

	public void setId(ExperienceDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seeker_id", nullable = false)
	public SeekerProfile getSeekerProfile() {
		return this.seekerProfile;
	}

	public void setSeekerProfile(SeekerProfile seekerProfile) {
		this.seekerProfile = seekerProfile;
	}

	@Column(name = "company_name", nullable = false, length = 100)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "position", nullable = false, length = 100)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "description", length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "is_current_job", nullable = false)
	public boolean isIsCurrentJob() {
		return this.isCurrentJob;
	}

	public void setIsCurrentJob(boolean isCurrentJob) {
		this.isCurrentJob = isCurrentJob;
	}

	@Column(name = "image_path", length = 200)
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

}
