package employmentservices.model;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location")
public class Location implements java.io.Serializable {

	private int id;
	private String city;
	private String state;
	private Set<JobPost> jobPosts = new HashSet<JobPost>(0);
	private Set<SeekerProfile> seekerProfiles = new HashSet<SeekerProfile>(0);
	private Set<Company> companies = new HashSet<Company>(0);

	public Location() {
	}

	public Location(int id, String city, String state) {
		this.id = id;
		this.city = city;
		this.state = state;
	}

	public Location(int id, String city, String state, Set<JobPost> jobPosts, Set<SeekerProfile> seekerProfiles,
			Set<Company> companies) {
		this.id = id;
		this.city = city;
		this.state = state;
		this.jobPosts = jobPosts;
		this.seekerProfiles = seekerProfiles;
		this.companies = companies;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "city", nullable = false, length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", nullable = false, length = 50)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	public Set<JobPost> getJobPosts() {
		return this.jobPosts;
	}

	public void setJobPosts(Set<JobPost> jobPosts) {
		this.jobPosts = jobPosts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	public Set<SeekerProfile> getSeekerProfiles() {
		return this.seekerProfiles;
	}

	public void setSeekerProfiles(Set<SeekerProfile> seekerProfiles) {
		this.seekerProfiles = seekerProfiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	public Set<Company> getCompanies() {
		return this.companies;
	}

	public void setCompanies(Set<Company> companies) {
		this.companies = companies;
	}

}
