package employmentservices.model.company;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BusinessStream generated by hbm2java
 */
@Entity
@Table(name = "business_stream")
public class BusinessStream implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3863447623084456732L;
	private int id;
	private String businessStreamName;
	private Set<Company> companies = new HashSet<Company>(0);

	public BusinessStream() {
	}

	public BusinessStream(int id, String businessStreamName) {
		this.id = id;
		this.businessStreamName = businessStreamName;
	}

	public BusinessStream(int id, String businessStreamName, Set<Company> companies) {
		this.id = id;
		this.businessStreamName = businessStreamName;
		this.companies = companies;
	}

	@Id @GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "business_stream_generator")
	@SequenceGenerator(name="business_stream_generator", sequenceName = "business_stream_id_seq")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "business_stream_name", nullable = false, length = 100)
	public String getBusinessStreamName() {
		return this.businessStreamName;
	}

	public void setBusinessStreamName(String businessStreamName) {
		this.businessStreamName = businessStreamName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessStream")
	public Set<Company> getCompanies() {
		return this.companies;
	}

	public void setCompanies(Set<Company> companies) {
		this.companies = companies;
	}

}
