package employmentservices.model.user;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * UserLog generated by hbm2java
 */
@Entity
@Table(name = "user_log")
public class UserLog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 377480831917237267L;
	private int userAccountId;
	private UserAccount userAccount;
	private Date lastLoginDate;
	private Date lastJobApplyDate;

	public UserLog() {
	}

	public UserLog(UserAccount userAccount, Date lastLoginDate) {
		this.userAccount = userAccount;
		this.lastLoginDate = lastLoginDate;
	}

	public UserLog(UserAccount userAccount, Date lastLoginDate, Date lastJobApplyDate) {
		this.userAccount = userAccount;
		this.lastLoginDate = lastLoginDate;
		this.lastJobApplyDate = lastJobApplyDate;
	}

	@GenericGenerator(name = "employmentservices.model.UserLogIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "userAccount"))
	@Id
	@GeneratedValue(generator = "employmentservices.model.UserLogIdGenerator")

	@Column(name = "user_account_id", unique = true, nullable = false)
	public int getUserAccountId() {
		return this.userAccountId;
	}

	public void setUserAccountId(int userAccountId) {
		this.userAccountId = userAccountId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern="dd.MM.yyyy")
	@Column(name = "last_login_date", nullable = false, length = 13)
	public Date getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern="dd.MM.yyyy")
	@Column(name = "last_job_apply_date", length = 13)
	public Date getLastJobApplyDate() {
		return this.lastJobApplyDate;
	}

	public void setLastJobApplyDate(Date lastJobApplyDate) {
		this.lastJobApplyDate = lastJobApplyDate;
	}

}
